#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$PWD"
USER_HOME="$HOME"

CONFIG_DIR="${USER_HOME}/.config"
CONFIG_DIR_OLD="${CONFIG_DIR}.old"

FILES=(
  'bash/bashrc'
  'bash/bash_logout'
  'bash/profile'
  'vim/vimrc'
)

update_profile() {
  if [ ! -d "$USER_HOME" ]; then return 1; fi

  if [ -d "$CONFIG_DIR" ]; then
    if git -C "$CONFIG_DIR" rev-parse --is-inside-work-tree &>/dev/null; then
      if [[ "$(git -C "$CONFIG_DIR" remote get-url --no-all origin)" != *dot_server* ]]; then
        echo "Unknown dot files installation. Aborting." && return 1
      fi
    fi
    if [ ! "$CONFIG_DIR" -ef "$SCRIPT_DIR" ]; then
      mv "$CONFIG_DIR" "$CONFIG_DIR_OLD"
      mv "$SCRIPT_DIR" "$CONFIG_DIR"
    fi
  fi

  for _file in "${FILES[@]}"; do
    local filename="${_file##*/}"
    local home_filename="${USER_HOME}/.${filename}"
    local dots_filename="${CONFIG_DIR}/${_file}"

    if [ -L "$home_filename" ]; then
      rm "$home_filename"
    elif [ -f "$home_filename" ]; then
      [ ! -d "$CONFIG_DIR_OLD" ] && mkdir -p "$CONFIG_DIR_OLD"
      if [ -d "$CONFIG_DIR_OLD" ]; then
        mv "$home_filename" "${CONFIG_DIR_OLD}/${home_filename##/*}"
      fi
    fi

    ln -s "$dots_filename" "$home_filename"
  done

  [ -f "${USER_HOME}/.viminfo" ] && rm "${USER_HOME}/.viminfo"

  printf 'Success.\n'
}

if [ "${#BASH_SOURCE[@]}" -eq 1 ]; then
  update_profile
fi
