" References:
" - sensible.vim
" - https://www.freecodecamp.org/news/vimrc-configuration-guide-customize-your-vim-editor/
" - https://github.com/YanivZalach/Vim_Config_NO_PLUGINS/blob/main/.vimrc
" - https://github.com/blaenk/dots/blob/master/vim/.vimrc
" - https://stackoverflow.com/questions/48271865/vim-whats-the-best-way-to-set-statusline-color-to-change-based-on-mode
" - https://github.com/noahfrederick/vim-noctu/blob/master/colors/noctu.vim


" GENERAL {{{

" Disable vi compatibility, if for some reason it's on.
set nocompatible

" Default file encoding.
if has ('multi_byte')
  set encoding=utf-8
  scriptencoding utf-8
  set fileencodings=ucs-bom,utf-8,latin1
endif

" Default interface language.
if has('multi_lang')
  silent! language messages C
endif

if exists('&langmenu')
  set langmenu=none
endif

" Enable native mouse support.
if exists('&mouse')
  set mouse=a
endif

" SGR mouse support for older Vim/terminal setups.
" Modern Vim often auto-detects this; Neovim does not need this option.
if exists('&ttymouse') && has('mouse_sgr')
  set ttymouse=sgr
endif

" Do not load tohtml.vim
let g:loaded_2html_plugin = 1

" Enable the :Man command shipped inside Vim's man filetype plugin.
if exists(':Man') != 2 && !exists('g:loaded_man')
  runtime ftplugin/man.vim
endif

" Use less for keywordprg.
if empty($MANPAGER) || $MANPAGER !~# '^less\>'
  let $MANPAGER = 'less -R'
endif

if empty($PAGER) || $PAGER !~# '^less\>'
  let $PAGER = 'less'
endif

augroup user_keywordprg
  autocmd!
  autocmd FileType vim setlocal keywordprg=:help
augroup END

" }}}


" FILES {{{

" Enable type file detection &
" load indent file for the detected file type.
filetype plugin indent on

" Reload files changed outside vim.
set autoread

" Automatically :write before running commands.
set autowrite

"Return to last edit position when opening files.
function! GoToLastPosition() abort
  if &buftype !=# ''
    return
  endif
  if line("'\"") > 1 && line("'\"") <= line("$")
    silent! normal! g`"
  endif
endfunction

augroup user_go_to_last_position
  autocmd!
  autocmd BufReadPost * call GoToLastPosition()
augroup END

" Vim state directory.
let s:vim_state = expand('~/.local/state/vim')

if !empty(s:vim_state)
  try
    call mkdir(s:vim_state, 'p', 0700)
  catch
  endtry
endif

" OPT: Do not save backup files.
"set nobackup
"set nowritebackup
"set noswapfile

" Save backup & swap files to state dir.
if isdirectory(s:vim_state)
  let s:backup_dir = s:vim_state . '/backup'
  let s:swap_dir = s:vim_state . '/swap'

  try
    call mkdir(s:backup_dir, 'p', 0700)
    call mkdir(s:swap_dir, 'p', 0700)
  catch
  endtry

  if isdirectory(s:backup_dir)
    set backup
    set writebackup
    let &backupdir = s:backup_dir . '//'
  endif

  if isdirectory(s:swap_dir)
    set swapfile
    let &directory = s:swap_dir . '//'
  endif
endif

" Store vim state.
if isdirectory(s:vim_state)
  if exists('&viminfo')
    let &viminfo .= ',n' . s:vim_state . '/viminfo'
    if &viminfo !~# '!'
      set viminfo^=!
    endif
  endif

  " Keep undo history across sessions.
  if has('persistent_undo')
    let s:undo_dir = s:vim_state . '/undo'
    try
      call mkdir(s:undo_dir, 'p', 0700)
    catch
    endtry

    if isdirectory(s:undo_dir)
      let &undodir = s:undo_dir . '//'
      set undofile
    endif
  endif

  " Store netrw history.
  let g:netrw_home = s:vim_state
endif

" }}}


" EDITOR {{{

" Virtual edit for visual block edit.
set virtualedit=block

" Allow backspace in insert mode.
set backspace=indent,eol,start

"Time out on key codes but not mappings.
set notimeout
set timeoutlen=800
set ttimeout
set ttimeoutlen=100

" Max num of open tabs.
set tabpagemax=50

" Keep tabs in the bg.
set hidden

" Disable saving options in session and view files.
if exists('&sessionoptions')
  set sessionoptions-=options
endif

if exists('&viewoptions')
  set viewoptions-=options
endif

" Ignore certain files and folders when globbing
" Wild menu will ignore files with these extensions.
set wildignore+=*.docx,*.jpg,*.png,*.gif,*.pdf
set wildignore+=*.pyc,*.exe,*.flv,*.img,*.xlsx
set wildignore+=*.o,*.obj,*.bin,*.dll,*.exe
set wildignore+=*/.git/*,*/.svn/*,*/__pycache__/*,*/build/*
set wildignore+=*.pyc
set wildignore+=*.DS_Store
set wildignore+=*.aux,*.bbl,*.blg,*.brf,*.fls,*.fdb_latexmk,*.synctex.gz

" Delete comment character when joining commented lines.
set formatoptions+=c
set formatoptions+=q
set formatoptions+=j

" Correctly break multi-byte characters such as CJK.
" see https://stackoverflow.com/q/32669814/6064933
set formatoptions+=m
set formatoptions+=M

" Disable auto commenting on a new line.
augroup user_format_opts
  autocmd!
  autocmd Filetype * setlocal formatoptions-=c
        \ formatoptions-=r
        \ formatoptions-=o
augroup END

" Vim folds.
augroup user_fold_opts
  autocmd!
  autocmd FileType vim setlocal foldmethod=marker
        \ foldlevel=0
        \ foldlevelstart=-1
        \ keywordprg=:help
        \ formatoptions-=o
        \ formatoptions-=r
augroup END

" Enable fast tty support.
if exists('&ttyfast')
  set ttyfast
endif

" For regular expressions backwards comp.
set magic

" Set regular expression engine.
if exists('&regexpengine')
  set regexpengine=0
endif

" Base number when c-A & C-x for adds and subs.
set nrformats-=octal

" Do not override restricted/nologin shells.
if exists('$SHELL') && $SHELL =~# '\v/(false|nologin)$'
  " Keep Vim's restricted behavior.
elseif executable('/usr/bin/bash')
  set shell=/usr/bin/bash
elseif executable('/bin/bash')
  set shell=/bin/bash
elseif executable('/bin/sh')
  set shell=/bin/sh
endif

" OPT: Keep swap warnings visible.
" set shortmess+=A

" Do not add two spaces after a period when joining lines or formatting texts.
" see https://stackoverflow.com/q/4760428/6064933
set nojoinspaces

" Specify the behavior when switching between buffers.
if exists('&switchbuf')
  set switchbuf=useopen,usetab,newtab
endif
if exists('&showtabline')
  set showtabline=2
endif

" Disable a legacy behavior that can break plugin maps.
if exists('&langremap') && &langremap
  set nolangremap
endif

" Load matchit.vim, but only if the user hasn't installed a newer version.
if !exists('g:loaded_matchit')
  silent! runtime macros/matchit.vim
endif

" Open help vertically.
command! -bar -nargs=* -complete=help Help vertical belowright help <args>

augroup user_move_help
  autocmd!
  autocmd FileType help wincmd L
augroup END

" Remove trailing white space.
" see https://vi.stackexchange.com/a/456/15292
function! StripTrailingWhitespaces() abort
  let l:save = winsaveview()
  keeppatterns silent! %s/[ \t]\+$//e
  call winrestview(l:save)
endfunction

nnoremap <leader>s :call StripTrailingWhitespaces()<CR>

" }}}


" INDENTATION {{{

" Disable autoindentation
"set noautoindent
"set nosmartindent
set autoindent
set smartindent

" Use tabs instead of space characters
set noexpandtab

" Set shift width to 2 spaces.
set shiftwidth=2

" Set tab width to 2 columns.
set tabstop=2

" Spaces a tab counts while editing
set softtabstop=2

" Inserts blanks according to shiftwidth
" set smarttab

" Align indent to next multiple value of shiftwidth.
" see http://vim.1045645.n5.nabble.com/shiftround-option-td5712100.html
set shiftround

" Do not wrap lines. Allow long lines to extend as far as the line goes.
" set nowrap

" Alt: Wrap lines at convenient points
set wrap
set textwidth=120
set linebreak
set showbreak=~>

" Display tabs and trailing spaces.
if &encoding ==# 'utf-8'
  set listchars=tab:┆\ ,trail:·,extends:>,precedes:<,nbsp:␣
else
  set listchars=tab:>\ ,trail:_,extends:>,precedes:<,nbsp:+
endif
set list

" }}}


" TERMINAL {{{

" Do not use smart case in command line mode.
" from: https://vi.stackexchange.com/q/16509/15292
if exists('##CmdLineEnter')
  augroup user_cmdline_smartcase
    autocmd!
    autocmd CmdLineEnter : let s:save_smartcase = &smartcase | set nosmartcase
    autocmd CmdLineLeave : if exists('s:save_smartcase') |
          \ let &smartcase = s:save_smartcase |
          \ unlet s:save_smartcase |
          \ endif
  augroup END
endif

" Do not use number and relative number for terminal inside vim
if exists('##TermOpen')
  augroup term_settings
    autocmd!
    autocmd TermOpen * setlocal norelativenumber nonumber
    autocmd TermOpen * startinsert
    autocmd BufEnter * if &buftype ==# 'terminal' <bar> startinsert <bar> endif
  augroup END
endif

" }}}


" SEARCH {{{

" While searching though a file incrementally highlight
" matching characters as you type.
set incsearch

" Ignore case in pattern by default
set ignorecase

" Use case-sensitive to search specifically for capital letters
set smartcase

" Show matching words during a search
set showmatch
set matchtime=2

" Use highlighting when doing a search
set hlsearch

" Set the commands to save in history default number is 20
set history=10000

" }}}


" COMPLETION {{{

" Disable completing keywords in included files (e.g., #include in C).
" When configured properly, this can result in the slow, recursive scanning of
" hundreds of files of dubious relevance.
set complete-=i

" Avoid scanning unloaded buffers.
set complete-=u

" Avoid tag completion.
set complete-=t
"set complete-=w
"set complete-=b

" Scan files given by `dictionary` option.
set complete+=k

" OPT: Enable Spelling Suggestions for Auto-Completion.
"set complete+=kspell

" Show menu even if there is only one item.
set completeopt+=menu,menuone

" Disable the preview window.
set completeopt-=preview

" Spell language.
set spelllang=en

" Enable omni complete features
augroup user_completion
  autocmd!
  autocmd FileType * if empty(&l:omnifunc) && exists('*syntaxcomplete#Complete') |
        \ setlocal omnifunc=syntaxcomplete#Complete |
        \ endif
augroup END

" Enhanced command-line completion mode w\ popup menu.
set wildmenu

" List all matches without completing, then each full match >vim.
set wildmode=list:longest,full

" Popup menu height.
set pumheight=8

" Search for ./tags upward through ancestor directories.
if has('path_extra') && (',' . &g:tags . ',') =~# ',\./tags,'
  setglobal tags-=./tags tags-=./tags; tags^=./tags;
endif

" Minimalist-Tab Completion.
fun! TabComplete() abort
  if pumvisible()
    return "\<C-n>"
  endif

  let l:col = col('.') - 1
  if l:col > 0 && getline('.')[l:col - 1] =~ '\k'
    return "\<C-n>"
  endif

  return "\<Tab>"
endfun

inoremap <expr> <Tab> TabComplete()

" }}}


" MAPPINGS {{{

let g:mapleader = " "
let g:maplocalleader = ','

" Source current vimrc file.
nnoremap <silent> <leader>cs :execute 'source' fnameescape(expand('%:p'))<CR>

" Quit.
nnoremap <silent> <leader>qq :quitall<CR>

" Redraw window.
nnoremap <silent> <leader>r :redraw!<CR>

" ESC in insert mode.
inoremap <silent> jk <ESC>
inoremap <silent> kj <ESC>

" Resize windows with arrow keys.
" from: https://vim.fandom.com/wiki/Fast_window_resizing_with_plus/minus_keys
nnoremap <silent> <C-Down>  <C-w>+
nnoremap <silent> <C-Up>    <C-w>-
nnoremap <silent> <C-Right> <C-w><
nnoremap <silent> <C-Left>  <C-w>>

" Move between windows.
nnoremap <silent> <C-j> <C-w>j
nnoremap <silent> <C-k> <C-w>k
nnoremap <silent> <C-h> <C-w>h
nnoremap <silent> <C-l> <C-w>l

" Buffer prev/next.
nnoremap <silent> <leader>j :bprev<CR>
nnoremap <silent> <leader>k :bnext<CR>
nnoremap <silent> <C-,> :bprev<CR>
nnoremap <silent> <C-.> :bnext<CR>

" Close the current buffer.
nnoremap <silent> <leader>bd :bdelete<CR>

" Move the cursor based on physical lines, not the actual lines.
nnoremap <silent> <expr> j v:count == 0 ? 'gj' : 'j'
nnoremap <silent> <expr> k v:count == 0 ? 'gk' : 'k'
nnoremap <silent> <expr> 0 v:count == 0 ? 'g0' : '0'
nnoremap <silent> <expr> ^ v:count == 0 ? 'g^' : '^'
nnoremap <silent> <expr> $ v:count == 0 ? 'g$' : '$'

" auto indent format.
nnoremap <silent> <leader>cf :normal! mzgg=G`z<CR>

" Disable search highlights.
nnoremap <silent> <leader>h :nohlsearch<CR>
nnoremap <silent> <Esc><Esc> :nohlsearch<CR>

" Continuous visual shifting (does not exit Visual mode).
" `gv` means to reselect previous visual area.
" see: https://superuser.com/q/310417/736190
xnoremap < <gv
xnoremap > >gv

" Make Y consistent with C and D.
nnoremap Y y$

" enable/disable paste mode, allows usign shortcuts like jk.
if exists('&pastetoggle')
  set pastetoggle=<F2>
endif

" From `:help :DiffOrig`.
if exists(':DiffOrig') != 2
  command! DiffOrig vertical new |
        \ setlocal bt=nofile |
        \ r ++edit # |
        \ 0d_ |
        \ diffthis |
        \ wincmd p |
        \ diffthis
endif

" Netrw options.
let g:netrw_banner = 0
let g:netrw_liststyle = 3  " default directory view. Cycle with i
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_sort_sequence = '[\/]$,*'
let g:netrw_keepdir = 0
let g:netrw_winsize = 25

" Open/close Netrw window.
nnoremap <silent> <leader>e :Lexplore<CR>

" Override default netrw's netrw_refresh <C-l>
" see: https://stackoverflow.com/questions/33351179/how-to-rewrite-existing-vim-key-bindings
nnoremap <unique> <C-~> <Plug>NetrwRefresh

" Open a terminal window.
if exists(':terminal') == 2
  nnoremap <silent> <C-/> :terminal<CR>
endif

" Close a terminal window.
tnoremap <silent> <C-/> <C-\><C-n>:bdelete!<CR>

" Esc to make the terminal scrollable,
" 'i' back to input mode.
tnoremap <silent> <Esc> <C-\><C-n>

" Show highlight group.
function! SynStack() abort
  if !exists("*synstack")
    echo 'synstack() is not available'
    return
  endif

  let l:stack = map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
  if empty(l:stack)
    echo 'No syntax group under cursor'
    return
  else
    echo 'stack: ' . join(l:stack, ' -> ')
  endif

  let l:id = synID(line('.'), col('.'), 1)
  echo 'effective: ' . synIDattr(l:id, 'name') . ' -> ' . synIDattr(synIDtrans(l:id), 'name')
endfunc

nnoremap <leader>; :call SynStack()<CR>

" Comment-toggle for blocks of code.
" https: //stackoverflow.com/questions/1676632/whats-a-quick-way-to-comment-uncomment-lines-in-vim
let s:comment_map = {
      \ 'ahk':          ';',
      \ 'bash_profile': '#',
      \ 'bashrc':       '#',
      \ 'bat':          'REM',
      \ 'c':            '//',
      \ 'conf':         '#',
      \ 'cpp':          '//',
      \ 'desktop':      '#',
      \ 'eml':          '>',
      \ 'fstab':        '#',
      \ 'go':           '//',
      \ 'java':         '//',
      \ 'javascript':   '//',
      \ 'lua':          '--',
      \ 'mail':         '>',
      \ 'php':          '//',
      \ 'profile':      '#',
      \ 'python':       '#',
      \ 'ruby':         '#',
      \ 'rust':         '//',
      \ 'scala':        '//',
      \ 'sh':           '#',
      \ 'tex':          '%',
      \ 'vim':          '"',
      \ }

function! s:CommentLeader() abort
  if &commentstring =~# '%s'
    let l:leader = substitute(&commentstring, '\s*%s.*$', '', '')
    if !empty(l:leader)
      return l:leader
    endif
  endif
  return get(s:comment_map, &filetype, '')
endfunction

function! ToggleCommentRange(first, last) abort
  let l:leader = s:CommentLeader()
  if empty(l:leader)
    echo 'No comment leader found for filetype: ' . &filetype
    return
  endif

  let l:leader_re = escape(l:leader, '\.^$~[]*')
  let l:all_commented = 1

  for l:num in range(a:first, a:last)
    let l:line = getline(l:num)
    if l:line =~# '^\s*$'
      continue
    endif
    if l:line !~# '^\s*' . l:leader_re
      let l:all_commented = 0
      break
    endif
  endfor

  for l:num in range(a:first, a:last)
    let l:line = getline(l:num)
    if l:line =~# '^\s*$'
      continue
    endif
    if l:all_commented
      call setline(l:num, substitute(l:line, '^\(\s*\)' . l:leader_re . '\s\?', '\1', ''))
    else
      call setline(l:num, substitute(l:line, '^\(\s*\)', '\1' . l:leader . ' ', ''))
    endif
  endfor
endfunction

nnoremap <silent> gcc :call ToggleCommentRange(line('.'), line('.'))<CR>
xnoremap <silent> gc :<C-u>call ToggleCommentRange(line("'<"), line("'>"))<CR>

" }}}


" UI {{{

" Show partial command you type in the last line of the screen.
set showcmd

" Hide the mode, we have a statusline.
set noshowmode

" Show current line number.
set number

" Show relative line numbers.
set relativenumber

" Show the cursor position all the time.
set ruler

" Do not let cursor scroll below or above N number of lines when scrolling.
set scrolloff=8

" Disable column highlight.
set nocursorcolumn

" Highlight current line number.
if exists('&cursorlineopt')
  set cursorline
  set cursorlineopt=number
endif

" Disable bells.
set noerrorbells
set novisualbell

if exists('&t_vb')
  set t_vb=
endif

" Disable modelines as a security precaution.
set modelines=0
set nomodeline

" Prefer splitting windows to the right.
set splitright
set splitbelow

" Do not hide markdown.
set conceallevel=0

" Command line height.
set cmdheight=1

" Adds 1 col space left to the numbers.
set foldcolumn=1

" Horizontal scrolling.
set sidescroll=1
set sidescrolloff=2

set display=lastline
"set display+=truncate

" have a fixed column for the diagnostics to appear in
" this removes the jitter when warnings/errors flow in.
if exists('&signcolumn')
  set signcolumn=yes
endif

" Hide tabline.
set showtabline=0

" Don't redraw while executing macros (good performance config).
" from: https://github.com/amix/vimrc/blob/master/vimrcs/basic.vim
set lazyredraw

" Cursor modes: Normal - Insert.
function! CursorShape() abort
  if has('gui_running')
    return
  endif

  if &term !~# '\v(xterm|screen|tmux|rxvt|st|alacritty|foot|kitty|linux|wezterm)'
    return
  endif

  let &t_SI = "\<esc>[6 q"
  let &t_EI = "\<esc>[2 q"

  if exists('&t_SR')
    let &t_SR = "\<esc>[4 q"
  endif
endfunction

function! CursorShapeReset() abort
  call CursorShape()
  silent! execute "normal! \<Esc>"
  silent! echon &t_EI
endfunction

" Reset the cursor on start.
augroup user_cursor_shape
  autocmd!
  autocmd VimEnter * call CursorShapeReset()
  autocmd VimLeave * silent! echon "\<ESC>[2 q"
augroup END

" }}}


" HIGHLIGHTS {{{

" Turn syntax highlighting on.
syntax enable
syntax sync minlines=256

if exists('&synmaxcol')
  set synmaxcol=300
endif

" Correctly highlight $() and other modern affordances in filetype=sh.
if !exists('g:is_posix') &&
      \ !exists('g:is_bash') &&
      \ !exists('g:is_kornshell')
      \ && !exists('g:is_dash')
  let g:is_posix = 1
  " let g:is_bash = 1
endif

" Allow color schemes to do bright colors without forcing bold.
if !has('gui_running') && &t_Co < 256
  set t_Co=256
endif

function! CustomHighlights() abort
  " custom highlights
  hi user1                ctermfg=7      ctermbg=0      cterm=NONE
  hi user2                ctermfg=7      ctermbg=8      cterm=NONE
  hi user3                ctermfg=10     ctermbg=8      cterm=NONE
  hi user4                ctermfg=0      ctermbg=2      cterm=bold
  hi user5                ctermfg=3      ctermbg=0      cterm=bold
  hi user6                ctermfg=8      ctermbg=NONE   cterm=NONE
  hi user7                ctermfg=NONE   ctermbg=NONE

  " status line
  hi StatusLine           ctermfg=0      ctermbg=NONE   cterm=bold
  hi StatusLineNC         ctermfg=NONE   ctermbg=NONE   cterm=italic
  hi StatusLineTerm       ctermfg=NONE   ctermbg=NONE   cterm=NONE
  hi StatusLineTermNC     ctermfg=NONE   ctermbg=NONE   cterm=NONE

  hi NormalMode           ctermfg=0      ctermbg=2      cterm=bold
  hi InsertMode           ctermfg=0      ctermbg=12     cterm=bold
  hi ReplaceMode          ctermfg=0      ctermbg=11     cterm=bold
  hi VisualMode           ctermfg=0      ctermbg=5      cterm=bold
  hi CommandMode          ctermfg=0      ctermbg=12     cterm=bold
  hi Warnings             ctermfg=3      ctermbg=0      cterm=bold

  hi Normal               ctermfg=7      ctermbg=NONE   cterm=NONE
  hi Cursor               ctermfg=NONE   ctermbg=NONE   cterm=reverse
  hi CursorIM             ctermfg=NONE   ctermbg=NONE   cterm=reverse
  hi CursorLine           ctermfg=NONE   ctermbg=NONE   cterm=NONE
  hi CursorLineNr         ctermfg=6      ctermbg=NONE   cterm=NONE
  hi CursorLineSign       ctermfg=13     ctermbg=NONE   cterm=NONE
  hi Matchparen           ctermfg=15     ctermbg=NONE   cterm=underline
  hi Pmenu                ctermfg=8      ctermbg=NONE
  hi PmenuThumb           ctermfg=8      ctermbg=NONE
  hi PmenuSbar            ctermfg=7      ctermbg=NONE
  hi PmenuSel             ctermfg=4      ctermbg=NONE
  hi ColorColumn          ctermfg=8      ctermbg=0
  hi SpellBad             ctermfg=1      ctermbg=NONE   cterm=underline
  hi SpellCap             ctermfg=10     ctermbg=NONE   cterm=underline
  hi SpellRare            ctermfg=11     ctermbg=NONE   cterm=underline
  hi SpellLocal           ctermfg=13     ctermbg=NONE   cterm=underline
  hi NonText              ctermfg=8
  hi LineNr               ctermfg=8      ctermbg=NONE   cterm=NONE
  hi Visual               ctermfg=NONE   ctermbg=0      cterm=NONE
  hi IncSearch            ctermfg=0      ctermbg=13     cterm=NONE
  hi Search               ctermfg=0      ctermbg=11
  hi VertSplit            ctermfg=0      ctermbg=NONE   cterm=NONE
  hi TabLine              ctermfg=0      ctermbg=NONE   cterm=NONE
  hi TabLineFill          ctermfg=0      ctermbg=NONE   cterm=NONE
  hi TabLineSel           ctermfg=7      ctermbg=0
  hi Folded               ctermfg=6      ctermbg=0      cterm=bold
  hi Conceal              ctermfg=8      ctermbg=NONE
  hi Directory            ctermfg=4                     cterm=bold
  hi Title                ctermfg=3                     cterm=bold
  hi ErrorMsg             ctermfg=9      ctermbg=NONE
  hi DiffAdd              ctermfg=0      ctermbg=10     cterm=bold
  hi DiffChange           ctermfg=0      ctermbg=11     cterm=bold
  hi DiffDelete           ctermfg=0      ctermbg=9      cterm=bold
  hi DiffText             ctermfg=0      ctermbg=13     cterm=bold
  hi WildMenu             ctermfg=6      ctermbg=NONE   cterm=bold
  hi EndOfBuffer          ctermfg=0      ctermbg=NONE   cterm=bold
  hi TrailingWhitespace   ctermfg=6      ctermbg=NONE
  hi ExtraWhitespace      ctermfg=0      ctermbg=NONE
  hi Whitespace           ctermfg=6      ctermbg=NONE
  hi SpecialKey           ctermfg=0      ctermbg=NONE

  hi! link CursorColumn   CursorLine
  hi! link SignColumn     LineNr
  hi! link FoldColumn     SignColumn
  hi! link WarningMsg     ErrorMsg
  hi! link MoreMsg        Title
  hi! link Question       MoreMsg
  hi! link ModeMsg        MoreMsg
  " hi! link tablinefill    vertsplit
  " hi! link specialkey     nontext

  " generic syntax
  hi Comment              ctermfg=8      ctermbg=NONE   cterm=NONE
  hi Constant             ctermfg=3      ctermbg=NONE   cterm=NONE
  hi String               ctermfg=2      ctermbg=NONE   cterm=NONE
  hi! link Character      String
  hi Number               ctermfg=3      ctermbg=NONE   cterm=NONE
  hi! link Boolean        Number
  hi! link Float          Number
  hi Identifier           ctermfg=7      ctermbg=NONE   cterm=NONE
  hi Function             ctermfg=4      ctermbg=NONE   cterm=NONE
  hi Statement            ctermfg=5      ctermbg=NONE   cterm=NONE
  hi! link Operator       Identifier
  hi Keyword              ctermfg=5
  hi Preproc              ctermfg=11     ctermbg=NONE   cterm=NONE
  hi Include              ctermfg=5      ctermbg=NONE   cterm=NONE
  hi! link Define         Include
  hi! link Macro          Include
  hi! link PreCondit      Include
  hi Type                 ctermfg=11     ctermbg=NONE   cterm=NONE
  hi Special              ctermfg=9      ctermbg=NONE   cterm=NONE
  hi SpecialChar          ctermfg=6      ctermbg=NONE   cterm=NONE
  hi! link Tag            Special
  hi! link Delimiter      Identifier
  hi SpecialComment       ctermfg=14     ctermbg=NONE   cterm=italic
  hi Debug                ctermfg=11     ctermbg=NONE   cterm=bold,italic
  hi Underlined           ctermfg=4      ctermbg=NONE   cterm=underline
  hi Ignore               ctermfg=8      ctermbg=NONE   cterm=NONE
  hi! link Error          ErrorMsg
  hi Todo                 ctermfg=5      ctermbg=NONE   cterm=bold,italic

  " help
  hi! link HelpExample                   String
  hi! link HelpHeadline                  Title
  hi! link HelpSectionDelim              Comment
  hi! link HelpHypertextEntry            Statement
  hi! link HelpHypertextJump             Underlined
  hi! link HelpUrl                       Underlined

  " vim
  hi! link VimSetSep                     Delimiter
  hi! link VimContinue                   Delimiter
  hi! link VimHiAttrib                   Constant

  " netrw
  hi netrwExe                            ctermfg=9
  hi netrwClassify                       ctermfg=8  cterm=bold

  " diff
  hi DiffAdded                           ctermfg=2
  hi DiffRemoved                         ctermfg=1
  hi! link DiffFile                      preproc
  hi! link DiffLine                      title

  " git
  hi GitCommitBranch                     ctermfg=3
  hi GitCommitSelectedtype               ctermfg=10
  hi GitCommitSelectedfile               ctermfg=2
  hi GitCommitUnmergedtype               ctermfg=9
  hi GitCommitUnmergedfile               ctermfg=1
  hi! link GitCommitFile                 Directory
  hi! link GitCommitUntrackedfile        GitCommitUnmergedFile
  hi! link GitCommitDiscardedtype        GitCommitUnmergedType
  hi! link GitCommitDiscardedfile        GitCommitUnmergedFile

  " markdown
  hi! markdownBold                       cterm=bold
  hi! markdownItalic                     cterm=italic
  hi! markdownBoldItalic                 cterm=bold,italic
  hi! markdownStrike                     cterm=strikethrough
  hi! markdownRule                       ctermfg=9   ctermbg=NONE   cterm=NONE
  hi! markdownCode                       ctermfg=2   ctermbg=NONE   cterm=NONE
  hi! link markdownCodeBlock             markdownCode
  hi! link markdownCodeDelimiter         markdownCode

  hi! markdownDelimiter                  ctermfg=7   ctermbg=NONE   cterm=NONE
  hi! markdownautomaticlink              ctermfg=7   ctermbg=NONE   cterm=NONE

  hi! markdownurl                        ctermfg=6   ctermbg=NONE   cterm=underline
  hi! link markdownurldelimiter          markdownurl
  hi! markdownUrlTitle                   ctermfg=4   ctermbg=NONE   cterm=NONE
  hi! link markdownUrlTitleDelimiter     markdownUrlTitle
  hi! link markdownlinkdelimiter         markdownUrlTitle
  hi! link markdownlinktext              markdownUrlTitle
  hi! link markdownlinktextdelimiter     markdownUrlTitle

  hi! markdownHeadingRule                ctermfg=8   ctermbg=NONE   cterm=NONE
  hi! markdownHeadingDelimiter           ctermfg=1   ctermbg=NONE   cterm=bold
  hi! link markdownListMarker            markdownHeadingDelimiter

  hi! markdownH1                         ctermfg=9   ctermbg=NONE   cterm=bold
  hi! markdownH2                         ctermfg=5   ctermbg=NONE   cterm=bold
  hi! markdownH3                         ctermfg=3   ctermbg=NONE   cterm=bold
  hi! markdownH4                         ctermfg=1   ctermbg=NONE   cterm=bold
  hi! markdownH5                         ctermfg=5   ctermbg=NONE   cterm=bold
  hi! markdownH6                         ctermfg=3   ctermbg=NONE   cterm=bold
  hi! link markdownH1Delimiter           markdownH1
  hi! link markdownH2Delimiter           markdownH2
  hi! link markdownH3Delimiter           markdownH3
  hi! link markdownH4Delimiter           markdownH4
  hi! link markdownH5Delimiter           markdownH5
  hi! link markdownH6Delimiter           markdownH6

  hi! link markdownBlockquote            Comment
  hi! link markdownBoldDelimiter         markdownbold
  hi! link markdownBoldDelimiter         markdownbold
  hi! link markdownBoldItalicDelimiter   markdownBoldItalic
  hi! link markdownError                 Error
  hi! link markdownEscape                Special
  hi! link markdownFootnote              Typedef
  hi! link markdownFootnoteDefinition    Typedef
  hi! link markdownId                    Type
  hi! link markdownIdDeclaration         Typedef
  hi! link markdownIdDelimiter           markdownlinkdelimiter
  hi! link markdownItalicDelimiter       markdownitalic
  hi! link markdownLineBreak             cleared
  hi! link markdownLineStart             cleared
  hi! link markdownLink                  cleared
  hi! link markdownOrderedListMarker     markdownListMarker
  hi! link markdownStrike                htmlStrike
  hi! link markdownStrikeDelimiter       markdownStrike
  hi! link markdownValid                 cleared
  hi! link markdownYamlHead              cleared

  " yaml
  hi! yamlAlias                          ctermfg=9   ctermbg=NONE   cterm=NONE
  hi! yamlFlowIndicator                  ctermfg=2   ctermbg=NONE   cterm=NONE
  hi! yamlKeyValueDelimiter              ctermfg=8   ctermbg=NONE   cterm=NONE
  hi! yamlMappingKey                     ctermfg=6   ctermbg=NONE   cterm=NONE

  hi! link yamlAnchor                    yamlAlias
  hi! link yamlDocumentStart             yamlAlias
  hi! link yamlPlainScalar               yamlFlowIndicator
  hi! link yamlMappingKeyStart           yamlKeyValueDelimiter
  hi! link yamlMappingMerge              yamlAlias
  hi! link yamlFlowMappingKey            yamlMappingKey
  hi! link yamlFlowMappingKeyStart       yamlMappingKeyStart
  hi! link yamlFlowMappingMerge          yamlMappingMerge
  hi! link yamlBlockMappingKey           yamlMappingKey
  hi! link yamlBlockCollectionItemStart  yamlKeyValueDelimiter
  hi! link yamlBlockMappingKeyStart      yamlMappingKeyStart
  hi! link yamlBlockMappingMerge         yamlBlockMappingKey
  hi! link yamlFlowMappingDelimiter      yamlKeyValueDelimiter
  hi! link yamlBlockMappingDelimiter     yamlKeyValueDelimiter
  hi! link yamlConstant                  Constant
  hi! link yamlDirectiveName             Keyword

  " html
  hi htmltagname                         ctermfg=2
  hi htmltag                             ctermfg=2
  hi htmlarg                             ctermfg=10
  hi htmlh1                              ctermfg=1  cterm=bold
  hi htmlbold                            cterm=bold
  hi htmlitalic                          cterm=underline
  hi htmlunderline                       cterm=underline
  hi htmlbolditalic                      cterm=bold,underline
  hi htmlboldunderline                   cterm=bold,underline
  hi htmlunderlineitalic                 cterm=underline
  hi htmlboldunderlineitalic             cterm=bold,underline
  hi! link htmllink                      Underlined
  hi! link htmlendtag                    htmltag

  " xml
  hi xmltag                              ctermfg=5
  hi! link xmltagname                    xmltag
  hi! link xmlendtag                     xmltag
  hi! xmlDocType                         ctermfg=9
  hi! link xmlDocTypeDecl                xmltag
  hi! xmlDocTypeKeyword                  ctermfg=11
  hi! link xmlProcessingDelim            xmltag
  hi! xmlstring                          ctermfg=2
  hi! xmlattrib                          ctermfg=6
  hi! xmlequal                           ctermfg=9

  " javascript
  hi! link javascript                    Normal
  hi! link javascriptbraces              Delimiter

endfunction

augroup user_highlights
  autocmd!
  autocmd ColorScheme * call CustomHighlights()
augroup END

set background=dark
colorscheme default
call CustomHighlights()

function! s:SetupWhitespaceMatches() abort
  if exists('w:trailing_whitespace_match')
    silent! call matchdelete(w:trailing_whitespace_match)
  endif
  if exists('w:leading_tabs_match')
    silent! call matchdelete(w:leading_tabs_match)
  endif

  let w:trailing_whitespace_match = matchadd('TrailingWhitespace', '\s\+$')
  let w:leading_tabs_match = matchadd('ExtraWhitespace', '^\t\+')
endfunction

augroup user_whitespace_matches
  autocmd!
  autocmd WinEnter,BufWinEnter * call s:SetupWhitespaceMatches()
augroup END

call s:SetupWhitespaceMatches()

" disable syntax on large files
function! DisableHighlights() abort
  if getfsize(expand('%:p')) > 500000
    setlocal syntax=off
  endif
endfunction

augroup user_highlight_large_files
  autocmd!
  autocmd BufReadPost * call DisableHighlights()
augroup END

" }}}


" STATUSLINE {{{

" Always display the Statusline.
set laststatus=2

" Reset statusline.
set statusline=

" Statusline functions:
function! StatuslineMode() abort
  let l:mode=mode(1)

  if l:mode ==# 'n'
    return '%#NormalMode# NORMAL '
  elseif l:mode ==# 'no'
    return '%#NormalMode# NORMAL '
  elseif l:mode ==# 'i'
    return '%#InsertMode# INSERT '
  elseif l:mode ==# 'c'
    return '%#CommandMode# COMMAND '
  elseif l:mode ==# 'v'
    return '%#VisualMode# VISUAL '
  elseif l:mode ==# 'V'
    return '%#VisualMode# V-LINE '
  elseif l:mode ==# "\<C-v>"
    return '%#VisualMode# V-BLOCK '
  elseif l:mode ==# 'R'
    return '%#ReplaceMode# REPLACE '
  elseif l:mode ==# 'Rv'
    return '%#ReplaceMode# V-REPLACE '
  elseif l:mode ==# 's'
    return '%#VisualMode# SELECT '
  elseif l:mode ==# 'S'
    return '%#VisualMode# S-LINE '
  elseif l:mode ==# "\<C-s>"
    return '%#VisualMode# S-BLOCK '
  elseif l:mode ==# 't'
    return '%#StatusLineTerm# TERM '
  elseif l:mode ==# '!'
    return '%#Warnings# SHELL '
  endif
  return '%#StatusLine# ' . l:mode . ' '
endfunction

" File name or else.
function! StatuslineFile() abort
  if empty(expand('%'))
    return '[No file]'
  endif
  return fnamemodify(getcwd(), ':~') . '/' . expand('%')
endfunction

" Read git branch if any.
function! GitBranch() abort
  let l:dir = expand('%:p:h')
  if empty(l:dir)
    let l:dir = getcwd()
  endif

  let l:git_dir = finddir('.git', l:dir . ';')
  if empty(l:git_dir)
    return ''
  endif

  let l:head = fnamemodify(l:git_dir, ':h') . '/.git/HEAD'
  if !filereadable(l:head)
    return ''
  endif

  let l:line = get(readfile(l:head, '', 1), 0, '')
  if l:line =~# '^ref: refs/heads/'
    return substitute(l:line, '^ref: refs/heads/', '', '')
  endif

  if !empty(l:line)
    return strpart(l:line, 0, 7)
  endif

  return ''
endfunction

" Show git branch if any.
function! StatuslineGit() abort
  let l:branch = GitBranch()
  return empty(l:branch) ? '' : l:branch . '*'
endfunction

" Build active Statusline
function! StatuslineActive() abort
  let l:line = ''

  " add buffer num
  if &buftype ==# 'terminal' ||
        \ &filetype ==# 'netrw' ||
        \ &filetype ==# 'help'
    return StatuslineInactive()
  else
    let l:line .= '%1* %n '
  endif
  " add vim mode & color
  let l:line .= StatuslineMode()
  " add git branch
  let l:branch = StatuslineGit()
  if !empty(l:branch)
    let l:line .= '%3* ' . l:branch . ' '
  endif
  " add server hostname
  if exists('$SSH_TTY')
    let l:line .= '%5* @' . hostname() . ' '
  endif
  " add filename
  let l:line .= '%1* %{StatuslineFile()}'
  " add file modified/readonly/top-bottom flag
  let l:line .= ' %m%r%w'
  " add separation
  let l:line .= '%1* %='
  " add paste indicator
  let l:line .= '%5*  %{&paste ? " [PASTE] " : ""}'
  " add file encoding + format + filetype
  let l:line .= '%2*  %{empty(&fileencoding) ? &encoding : &fileencoding}'
  let l:line .= '%2*  %{&fileformat}'
  let l:line .= '%3*  %{empty(&filetype) ? "noft" : &filetype}  '
  " add row:col
  let l:line .= '%4*  %l:%c  %6*'

  return l:line
endfunction

function! StatuslineInactive() abort
  return '%7* '
endfunction

" Statusline loader.
function! StatuslineLoad(mode) abort
  if a:mode ==# 'active'
    setlocal statusline=%!StatuslineActive()
  else
    setlocal statusline=%!StatuslineInactive()
  endif
endfunction

" Disable statusline for terminal, netwr and help buffers.
augroup user_statusline
  autocmd!
  autocmd WinEnter,BufWinEnter * call StatuslineLoad('active')
  autocmd WinLeave,BufWinLeave * call StatuslineLoad('inactive')
  if has ('ModeChanged')
    autocmd ModeChanged * redrawstatus
  endif
  autocmd FileType netrw setlocal nolist
augroup END

call StatuslineLoad('active')

" }}}


" LF INTEGRATION {{{

" a gem found in /usr/share/vim/vimfiles/syntax/lf.vim
if executable('lf')

  function! LF() abort
    let l:temp = tempname()

    execute 'silent !lf -selection-path=' . shellescape(l:temp)
    if v:shell_error
      redraw!
      echohl ErrorMsg
      echomsg 'lf exited with error'
      echohl None
      return
    endif

    if !filereadable(l:temp)
      redraw!
      return
    endif

    let l:names = readfile(l:temp)
    call delete(l:temp)

    if empty(l:names)
      redraw!
      return
    endif

    execute 'edit ' . fnameescape(l:names[0])
    for l:name in l:names[1:]
      execute 'argadd ' . fnameescape(l:name)
    endfor

    redraw!
  endfunction

  command! -bar LF call LF()

  " Open lf to navigate files
  nnoremap <silent> <leader>l :LF<CR>
endif

" }}}

" vim:et:ts=2:sw=2:fdm=marker:fmr={{{,}}}
