#!/usr/bin/env bash
# adapted from github.com/rafi/.config

set -u

FILE="${1-}"
WIDTH="${2:-$(tput cols 2> /dev/null | 120)}"
HEIGHT="${3:-$(tput lines 2> /dev/null | 40)}"
OFFSET="${lf_user_preview_offset:-1}"

# View binary hexyl/hexdump
view_binary() {
	local len="$((WIDTH * HEIGHT))"

	if hash hexyl 2> /dev/null; then
		hexyl -n "$len" --border none "$FILE"
	elif hash hexdump 2> /dev/null; then
		hexdump -n "$len" -C "$FILE"
	else
		file --brief "$FILE"
	fi
	return $?
}

view_dir() {
  if command -v tree >/dev/null 2>&1; then
    tree -L 1 -a -F --dirsfirst -- "$FILE"
  else
    ls -la -- "$FILE"
  fi
}

view_sourcecode() {
  if command -v bat >/dev/null 2>&1; then
    local -a bat_preview=(
      --color=always
      --theme=TwoDark
      --style=plain
      --tabs=2
      --terminal-width "$WIDTH"
      --wrap=never
      --line-range="${OFFSET}:"
    )

    if [[ -f $FILE ]]; then
			bat_preview+=( "--line-range=${OFFSET}:" )
			bat "${bat_preview[@]}" "$FILE"
    else
      return 1
    fi

  else
    if [[ -f $FILE ]]; then
      sed -n "${OFFSET},$((OFFSET + HEIGHT))p" -- "$FILE"
    else
      return 1
    fi
  fi
}

main() {
	[[ -n $FILE ]] || exit 1

	if [[ -d $FILE ]]; then
		view_dir
		exit $?
	fi

	[[ -L "${FILE}" ]] && FILE="$(readlink "$FILE")"
	[[ -f "${FILE-}" ]] || exit 1

	case "$(file --dereference --mime-type --brief -- "$FILE")" in
    text/*|application/json|application/xml|application/x-sh|application/x-shellscript)
      view_sourcecode
      ;;
    *)
      printf 'File: %s\n' "$FILE"
      file --brief -- "$FILE"
      printf '\n'
      view_binary
      ;;
  esac
}

main "$@"

# vim: set ts=2 sw=2 tw=80 noet :
