#!/usr/bin/env bash
# shellcheck disable=2139

#----- general

alias c=clear
alias wget="wget --hsts-file $XDG_CACHE_HOME/wget-hsts"
alias gurl='git remote get-url --no-all ' # usually origin

#----- colors

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  alias ls="LC_COLLATE=C ls --color=auto --group-directories-first"
fi

if [[ "$OSTYPE" == "freebsd"* ]]; then
  alias ls="LC_COLLATE=C ls --color=auto"
fi

alias ip='ip -color=always'
alias grep='grep --color=auto --exclude-dir=.git'
alias diff='diff --minimal --color=always '


#----- dirs

alias ,conf="cd $XDG_CONFIG_HOME"
alias ,data="cd $XDG_DATA_HOME"
alias ,cache="cd $XDG_CACHE_HOME"
alias ,state="cd $XDG_STATE_HOME"


#----- Docker

if hash docker 2> /dev/null; then

  alias dk=docker
  alias dco='docker compose'

  alias dps='docker ps -a --format "table {{.Names}}\\t{{.Image}}\\t{{.Status}}\\t{{ .Ports }}\\t{{.RunningFor}}\\t{{.Command}}\\t{{ .ID }}" | cut -c-$(tput cols)'
  alias drm="docker rm $(docker ps -a --format='json' | jq '. | .Names' | sed -r 's/\"//g')"

  alias dis='docker inspect --format "{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}"'

  alias dim='docker images --format "table {{.Repository}}\\t{{.Tag}}\\t{{.ID}}\\t{{.Size}}\\t{{.CreatedSince}}"'
  alias dimp='docker image prune -f'

  alias dvl='docker volume ls -qf dangling=true'
  alias dvlr='docker volume ls -qf dangling=true | xargs docker volume rm'

  alias dtop='docker stats $(docker ps --format="{{.Names}}")'

  # shellcheck disable=2154
  alias dnet='docker network ls && echo && docker inspect --format "{{\$e := . }}{{with .NetworkSettings}} {{\$e.Name}}
  {{range \$index, \$net := .Networks}}  - {{\$index}}  {{.IPAddress}}
  {{end}}{{end}}" $(docker ps -q)'

  # shellcheck disable=2154
  alias dtag='docker inspect --format "{{.Name}}
  {{range \$index, \$label := .Config.Labels}}  - {{\$index}}={{\$label}}
  {{end}}" $(docker ps -q)'
fi
