#!/usr/bin/env bash
# shellcheck disable=1091

export LANG="en_US.UTF-8"
export LC_CTYPE="$LANG"
export LC_ALL="$LANG"
export COLORTERM=truecolor

# XDG directories
export XDG_CONFIG_HOME="$HOME/.config"
export  XDG_CACHE_HOME="$HOME/.cache"
export   XDG_DATA_HOME="$HOME/.local/share"
export  XDG_STATE_HOME="$HOME/.local/state"

[ -d "$XDG_CONFIG_HOME" ] || mkdir -m 0750 "$XDG_CONFIG_HOME"
[ -d "$XDG_CACHE_HOME" ]  || mkdir -m 0750 "$XDG_CACHE_HOME"
[ -d "$XDG_DATA_HOME" ]   || mkdir -m 0750 "$XDG_DATA_HOME"
[ -d "$XDG_STATE_HOME" ]  || mkdir -m 0750 "$XDG_STATE_HOME"

# Local binaries path
PATH="$HOME/.local/bin:$PATH:bin"

# dot_server binaries
if [[ "$OSTYPE" == "freebsd"* ]]; then
	PATH="$HOME/.config/bin/freeBSD:$PATH"
fi

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  ARCH="$(lscpu | grep 'Architecture' | cut -d ':' -f 2)"
  ARCH="${ARCH#"${ARCH%%[![:space:]]*}"}"

  case "$ARCH" in
    x86_64) ARCH="amd64" ;;
    aarch64) ARCH="arm64" ;;
    *) ARCH="amd64" ;;
  esac

	# adds .config/bin folder to PATH
	PATH="$HOME/.config/bin/linux_$ARCH:$PATH"
fi

# https://www.gnu.org/software/bash/manual/html_node/Readline-Init-File.html
export INPUTRC="$XDG_CONFIG_HOME/bash/inputrc"

# History settings
export HISTSIZE=20000
if [[ "$BASH" ]]; then
	export HISTFILE="$XDG_CACHE_HOME/bash_history"
	export HISTFILESIZE=15000000
	export HISTTIMEFORMAT="%F %T "
	export HISTIGNORE='pwd:jobs:ls:history:clear:r:ranger'
	export HISTCONTROL=ignoreboth
fi

# Pager and Editor
PAGER=$(which less)
MANPAGER=$PAGER

if hash vim 2> /dev/null; then
	EDITOR=$(which vim)
  SUDO_EDITOR=$EDITOR
	MANPAGER='vim +MANPAGER --not-a-term -'
fi

export EDITOR
export SUDO_EDITOR
export SYSTEMD_EDITOR=$EDITOR
export SELECTED_EDITOR=$EDITOR
export VISUAL=$EDITOR

export PAGER
export MANPAGER
export MANWIDTH=999
export LESS="-FiQMXRwJ --incsearch --no-vbell --status-col-width 1"
export LESSQUIET=1
export LESSCHARSET="UTF-8"
export LESSHISTFILE="$XDG_CACHE_HOME/less_history"

# wget stuff
export WGETRC="$XDG_CONFIG_HOME"/wget/wgetrc

#----- Utils

# docker config
if [ ! -e "/.dockerenv" ]; then
	if hash docker 2> /dev/null; then
		export DOCKER_CONFIG="${XDG_CONFIG_HOME}"/docker
	else
		USER_ID=$(id --user)
		export DOCKER_HOST=unix:///run/user/$USER_ID/docker.sock
		export DOCKERD_ROOTLESS_ROOTLESSKIT_FLAGS="-p 0.0.0.0:2376:2376/tcp"
	fi
fi

# rust
if [ -d "$XDG_DATA_HOME/rustup" ]; then
	export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
fi
if [ -d "$XDG_DATA_HOME/cargo" ]; then
	export CARGO_HOME="$XDG_DATA_HOME/cargo"
	PATH="$XDG_DATA_HOME/cargo/bin:$PATH"
fi

# python
export PYTHON_COLORS=1
export PYTHONUSERBASE="$XDG_DATA_HOME/python"
export PYTHON_HISTORY="$XDG_STATE_HOME/python/history"
export PYTHONPYCACHEPREFIX="$XDG_CACHE_HOME/python"

if hash pipx 2> /dev/null; then
	export PIPX_HOME="$XDG_DATA_HOME/python/pipx"
	export PIPX_BIN_DIR="$XDG_DATA_HOME/python/pipx/bin"
	PATH="${PIPX_BIN_DIR}:${PATH}"
fi

# node version manager
if [[ -s "$XDG_DATA_HOME/node/nvm.sh" ]]; then
	export NVM_DIR="$XDG_DATA_HOME/node"
fi

if hash npm 2> /dev/null; then
	export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
fi

# yarn builder
if hash yarn 2> /dev/null; then
	PATH="$XDG_DATA_HOME/yarn/global/node_modules/.bin/:$PATH"
	export YARN_GLOBAL_FOLDER="$XDG_DATA_HOME/yarn/berry"
	export YARN_CACHE_FOLDER="$XDG_CACHE_HOME/yarn"
	export YARN_ENABLE_TELEMETRY=0
fi

# php builder
if hash composer 2> /dev/null; then
	export COMPOSER_HOME="$XDG_CACHE_HOME/composer"
fi

# java, kotlin, gradle version manager
if [ -s "$XDG_DATA_HOME/sdkman/bin/sdkman-init.sh" ]; then
	export SDKMAN_DIR="$XDG_DATA_HOME/sdkman"
fi

# Java stuff
if hash java 2> /dev/null; then

	# Java XWayland blank screens fix
	export _JAVA_AWT_WM_NONREPARENTING=1

	# java TOOLS opts
	_JAVA_TOOL_OPTS=(
		"-Djava.util.prefs.userRoot=$HOME/.config/java"
		"-Dconfig.override_with_env_vars=true"
		"-Djava.net.preferIPv4Stack=true"
		"-Duser.timezone=UTC"
		"-Dquill.macro.log=false"
		"-XX:+PerfDisableSharedMem"
	)
	export JAVA_TOOL_OPTIONS="${JAVA_TOOL_OPTIONS} ${_JAVA_TOOL_OPTS[*]}"

	# java JDK opts
	_JDK_OPTS=(
		"-Dawt.useSystemAAFontSettings=on"
		"-Dawt.toolkit.name=WLToolkit"
		"-Dswing.aatext=true"
		"-Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel"
		"-Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel"
		"-Djdk.gtk.version=3"
		"-Dorg.lwjgl.glfw.libname=/usr/lib/libglfw.so"
		"-Dawt.java2d.uiScale.enabled=true"
		"-Dsun.java2d.opengl=true"
		"-Dsun.java2d.opengl.fbobject=false"
	)
	export JDK_JAVA_OPTIONS="${JDK_JAVA_OPTIONS} ${_JDK_OPTS[*]}"

	# gradle builder
	export GRADLE_USER_HOME="$XDG_DATA_HOME/gradle"
fi

# Prune PATH duplicates
# https://unix.stackexchange.com/questions/40749/remove-duplicate-path-entries-with-awk-command/149054#149054
PATH="$(perl -e 'print join(":", grep { not $seen{$_}++ } split(/:/, $ENV{PATH}))')"

# Export the final PATH
export PATH

# vim: set ts=2 sw=2 tw=80 ft=sh noet :
