#!/usr/bin/env bash

# cd to current dir on lf quit
lf() {
  export LF_CD_FILE=/var/tmp/.lfcd-$$
  command lf "${@}"
  if [ -s "$LF_CD_FILE" ]; then
    local DIR
    DIR="$(realpath "$(cat "$LF_CD_FILE")")"
    if [ "$DIR" != "$PWD" ]; then
      # echo "cd to $DIR"
      cd "$DIR" || exit
    fi
    rm "$LF_CD_FILE"
  fi
  unset LF_CD_FILE
}

# note ./here
nh() {
  filename="$(date +%U-%y%m%d-%H%M)"
  "${EDITOR}" "${filename}.md"
}

# single-thread compiler-runer
cr() {
  if [ -f "$1" ]; then
    filename=${1%*.?}
    case $2 in
      gcc)
        if hash gcc 2> /dev/null; then
          gcc -Wall -g "$1" -lm -o "${filename}"
        else echo "No gcc binary found"; fi
        ;;
      clang)
        if hash clang 2> /dev/null; then
          clang -Wall -g "$1" -lm -o "${filename}"
        else echo "No clang binary found"; fi
        ;;
      *)
        if hash gcc 2> /dev/null; then
          gcc -Wall -g "$1" -lm -o "${filename}"
        else echo "No gcc binary found"; fi
        ;;
    esac
  else echo "No .c file found"; fi
}

# multi-thread compiler-runer
crt() {
  # clear;
  if [ -f "$1" ]; then
    filename=${1%*.?}
    if hash gcc 2> /dev/null; then
      gcc -pthread -Wall -g "$1" -lm -o "${filename}"
    else echo "No gcc binary found"; fi
  else echo "No .c file found"; fi
}

# java compiler
jc() {
  if [[ -d "./src/${1}" ]]; then
    dirpath="./src/${1}"
    if hash javac 2> /dev/null; then
      javac -d ./bin "${dirpath}"/*.java
    else echo "No java binaries found"; fi
  else echo "No directory name \"./src/${1}\" found"; fi
}

# java runner
jr() {
  if [[ -d "./bin/${1}" ]]; then
    dirname="${1}"
    if hash java 2> /dev/null; then
      java -cp ./bin "${dirname}".Program
    else echo "No java binaries found"; fi
  else echo "No directory name \"./bin/${1}\" found"; fi
}
