#!/usr/bin/env bash
# shellcheck disable=SC1091

# Amazing Fuzzy finder
if hash fzf 2> /dev/null; then
  fzf_keymaps=(
    ctrl-d:half-page-down
    ctrl-u:half-page-up
    ctrl-n:preview-down
    ctrl-p:preview-up
    ctrl-t:toggle-preview-wrap
    ctrl-y:yank
    ctrl-space:toggle+down
    tab:toggle+down
  )
  keymaps="$(printf ",%s" "${fzf_keymaps[@]}")"

  export FZF_DEFAULT_OPTS="
    --layout=reverse --margin=1 --info=inline-right --separator=- --no-height --bind ${keymaps:1}
    --color=fg:7,fg+:3
    --color=bg:#1e222a,bg+:#1e222a
    --color=hl:4,hl+:11
    --color=info:14,marker:6
    --color=prompt:9,spinner:5
    --color=pointer:9,header:2
    --color=border:#1e222a,list-border:8
    --color=label:3,query:7
    --color=preview-border:8,preview-scrollbar:#1e222a
    --border=rounded
    --border-label=''
    --preview-window=border-rounded
    --prompt='> '
    --marker='+'
    --pointer='>>'
    --separator='─'
    --scrollbar='│'"

  if hash rg 2> /dev/null; then
    export FZF_DEFAULT_COMMAND="
      rg --vimgrep --files --follow --hidden --no-ignore-vcs --smart-case --glob !**/.git/*"
  fi
 
  unset fzf_keymaps keymaps
  eval "$(fzf --bash)"
fi
