#!/usr/bin/env bash
# shellcheck disable=1091

# Amazing Fuzzy finder
if hash fzf 2> /dev/null; then
  fzf_keymaps=(
    ctrl-d:half-page-down
    ctrl-u:half-page-up
    ctrl-b:preview-down
    ctrl-n:preview-up
    ctrl-h:preview-half-page-down
    ctrl-l:preview-half-page-up
    ctrl-t:toggle-preview-wrap
    ctrl-space:toggle+down
    tab:toggle+down
  )
  keymaps="$(printf ",%s" "${fzf_keymaps[@]}")"

  export FZF_DEFAULT_OPTS="
    --layout=reverse --margin=1 --info=inline-right --separator=- --no-height
    --bind ${keymaps:1}
    --color=fg:7,fg+:3
    --color=bg:#1e222a,bg+:#1e222a
    --color=hl:4,hl+:11
    --color=info:14,marker:6
    --color=prompt:9,spinner:5
    --color=pointer:9,header:2
    --color=border:#1e222a,list-border:8
    --color=label:3,query:7
    --color=preview-border:8,preview-scrollbar:#1e222a
    --border=rounded
    --border-label=''
    --preview-window=border-rounded
    --prompt='> '
    --marker='+'
    --pointer='>>'
    --separator='─'
    --scrollbar='│'"

  width=80

  # shellcheck disable=2016
  opener='
    case $(file --dereference --mime-type "$file" -b) in
      application/json) $EDITOR "$file" ;;
      text/*)           $EDITOR "$file" ;;
      *)                return 1 ;;
    esac'

  if hash rg 2> /dev/null; then
    # files
    FZF_DEFAULT_COMMAND="rg --vimgrep --files --follow --hidden --no-ignore-vcs --smart-case --glob !**/.git/* --glob !**/.cache/* --"
  else
    # files
    FZF_DEFAULT_COMMAND="grep --dereference-recursive --binary-files=without-match --files-with-matches --exclude !**/.git/* --exclude !**/.cache/* --with-filename -- ."
  fi

  export FZF_DEFAULT_COMMAND
  export FZF_CTRL_T_COMMAND=$FZF_DEFAULT_COMMAND

  export FZF_CTRL_T_OPTS="
    --walker-skip .git,node_modules,target,.cache
    --bind 'enter:execute-silent($opener)'
    --preview-window "right,$width"
    --preview '$XDG_CONFIG_HOME/lf/preview {}'"

  export FZF_ALT_C_OPTS="
    --walker-skip .git,node_modules,target,.cache
    --bind 'enter:execute(lf {})+accept+close'
    --preview-window "right,$width"
    --preview 'tree -L 1 -l -d -s -h --du -C {}'"

  unset fzf_keymaps keymaps width opener
  eval "$(fzf --bash)"
fi
