#!/usr/bin/env bash
# shellcheck disable=SC1091

# Amazing Fuzzy finder
if hash fzf 2> /dev/null; then
  fzf_keymaps=(
    ctrl-d:half-page-down
    ctrl-u:half-page-up
    ctrl-n:preview-down
    ctrl-p:preview-up
    ctrl-t:toggle-preview-wrap
    ctrl-y:yank
    ctrl-space:toggle+down
    tab:toggle+down
  )
  keymaps="$(printf ",%s" "${fzf_keymaps[@]}")"

  # COLOR_BG=#1e222a
  # COLOR_FG=#abb2bf
  # COLOR_0=#2d3343
  # COLOR_1=#be5046
  # COLOR_2=#98c379  # #98c379 green
  # COLOR_3=#d19a66  # #d19a66 yellow
  # COLOR_4=#61afef  # #61afef blue
  # COLOR_5=#c678dd  # #c678dd magenta
  # COLOR_6=#56b6c2  # #56b6c2 cyan
  # COLOR_7=#abb2bf  # #abb2bf white
  # COLOR_8=#546178  # #546178 bright black
  # COLOR_9=#e06c75  # #e06c75 bright red
  # COLOR_10=#ace98e  # #ace98e bright green
  # COLOR_11=#e5c07b  # #e5c07b bright yellow
  # COLOR_12=#73ccfe  # #73ccfe bright blue
  # COLOR_13=#da9ef2  # #da9ef2 bright magenta
  # COLOR_14=#7adcd7  # #7adcd7 bright cyan
  # COLOR_15=#cdceee  # #cdceee bright white

  export FZF_DEFAULT_OPTS="
    --layout=reverse --margin=1 --info=inline-right --separator=- --no-height --bind ${keymaps:1}
    --color=fg:7,fg+:3
    --color=bg:#1e222a,bg+:#1e222a
    --color=hl:4,hl+:11
    --color=info:14,marker:6
    --color=prompt:9,spinner:5
    --color=pointer:9,header:2
    --color=border:#1e222a,list-border:8
    --color=label:3,query:7
    --color=preview-border:8,preview-scrollbar:#1e222a
    --border=rounded
    --border-label=''
    --preview-window=border-rounded
    --prompt='> '
    --marker='+'
    --pointer='>>'
    --separator='─'
    --scrollbar='│'"

  if hash rg 2> /dev/null; then
    export FZF_DEFAULT_COMMAND="
      rg --vimgrep --files --follow --hidden --no-ignore-vcs --smart-case --glob !**/.git/*"
  fi
 
  unset fzf_keymaps keymaps
  eval "$(fzf --bash)"
fi
