#!/usr/bin/env bash

if [ -z "$(LC_ALL=C type -t __git_ps1)" ]; then
	__git_ps1() {
		echo ''
	}
fi

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  # Load directory and file colors for GNU ls
  eval "$(dircolors -b "$XDG_CONFIG_HOME/dircolors/default")"
  if [[ -z "${LS_COLORS}" ]]; then
    LS_COLORS="$(dircolors -b "$XDG_CONFIG_HOME/dircolors/default")"
    export LS_COLORS
  fi
fi

# if [[ "$OSTYPE" == "freebsd"* ]]; then
# 	PATH="$XDG_CONFIG_HOME/bin/freeBSD:$PATH"
# fi

if [ -n "$SSH_TTY" ]; then
	PS1='\[\033[01;33m\]\u@\h \[\033[01;32m\]\W\[\033[01;36m\]$(__git_ps1 " %s")\[\033[49m\]\[\033[01;32m\] \$\[\033[00m\] '
else
	PS1='\[\033[01;32m\]\W\[\033[01;36m\]$(__git_ps1 " %s")\[\033[49m\]\[\033[01;32m\] \$\[\033[00m\] '
fi
