#!/usr/bin/env bash

# Fuzzy folder jump with $z folder_name
if hash zoxide 2>/dev/null; then
  # print match path when jumping
  export _ZO_ECHO=1
  export _ZO_DATA_DIR="$XDG_CACHE_HOME/zoxide"
  eval "$(zoxide init bash)"
fi

# Use keychain to persist ssh keys
# https://github.com/funtoo/keychain
if hash keychain 2>/dev/null; then
  eval "$(keychain --eval --quiet --ssh-allow-gpg --systemd)"
fi

# Java, kotlin, gradle version manager
sdk() {
  if [ -f "$XDG_DATA_HOME/sdkman/bin/sdkman-init.sh" ]; then
    if [[ "$XDG_DATA_HOME/sdkman/bin/sdkman-init.sh" != "${0}" ]]; then
      . "$XDG_DATA_HOME/sdkman/bin/sdkman-init.sh"
    fi
    sdk "$@"
  fi
}

# Node version manager
nvm() {
  if [ -f "$XDG_DATA_HOME/node/nvm.sh" ]; then
    if [[ "$XDG_DATA_HOME/node/nvm.sh" != "${0}" ]]; then 
      . "$XDG_DATA_HOME/node/nvm.sh"
    fi
    nvm "$@"
  fi
}
